services:
  vaultwarden:
    image: vaultwarden/server:1.32.5
    restart: unless-stopped




    volumes:
      - /opt/cloud-forge/data/vaultwarden:/data

    networks:
      - cloud-forge

networks:
  cloud-forge:
    name: cloud-forge
