services:
  nginx:
    image: nginx:${CLOUD_FORGE_APP_VERSION:-1.27-alpine}
    restart: unless-stopped
    volumes:
      - /opt/cloud-forge/data/nginx/html:/usr/share/nginx/html:ro
    networks:
      - cloud-forge

networks:
  cloud-forge:
    name: cloud-forge
