services:
  it_tools:
    image: corentinth/it-tools@sha256:8b8128748339583ca951af03dfe02a9a4d7363f61a216226fc28030731a5a61f
    restart: unless-stopped





    networks:
      - cloud-forge

networks:
  cloud-forge:
    name: cloud-forge
