services:
  sonarqube:
    image: sonarqube:lts-community
    restart: unless-stopped




    volumes:
      - /opt/cloud-forge/data/sonarqube:/opt/sonarqube/data

    networks:
      - cloud-forge

networks:
  cloud-forge:
    name: cloud-forge
