services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    restart: unless-stopped




    volumes:
      - /opt/cloud-forge/data/keycloak:/opt/keycloak/data

    networks:
      - cloud-forge

networks:
  cloud-forge:
    name: cloud-forge
