services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.15.0
    restart: unless-stopped




    volumes:
      - /opt/cloud-forge/data/audiobookshelf/config:/config

    networks:
      - cloud-forge

networks:
  cloud-forge:
    name: cloud-forge
