services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.20.1
    restart: unless-stopped


    env_file:
      - /opt/cloud-forge/compose.app.env

    volumes:
      - /opt/cloud-forge/data/mealie:/app/data

    networks:
      - cloud-forge

networks:
  cloud-forge:
    name: cloud-forge
