services:
  ntfy:
    image: binwiederhier/ntfy:2.11.0
    restart: unless-stopped




    volumes:
      - /opt/cloud-forge/data/ntfy:/var/cache/ntfy

    networks:
      - cloud-forge

networks:
  cloud-forge:
    name: cloud-forge
