services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    restart: unless-stopped




    volumes:
      - /opt/cloud-forge/data/jenkins:/var/jenkins_home

    networks:
      - cloud-forge

networks:
  cloud-forge:
    name: cloud-forge
