services:
  gitea:
    image: gitea/gitea:1.22.4
    restart: unless-stopped




    volumes:
      - /opt/cloud-forge/data/gitea:/data

    networks:
      - cloud-forge

networks:
  cloud-forge:
    name: cloud-forge
