services:
  matomo:
    image: matomo:5.2.2-apache
    restart: unless-stopped




    volumes:
      - /opt/cloud-forge/data/matomo:/var/www/html

    networks:
      - cloud-forge

networks:
  cloud-forge:
    name: cloud-forge
