services:
  code_server:
    image: codercom/code-server:4.96.2
    restart: unless-stopped


    env_file:
      - /opt/cloud-forge/compose.app.env
    volumes:
      - /opt/cloud-forge/data/code-server:/home/coder

    networks:
      - cloud-forge

networks:
  cloud-forge:
    external: true
