services:
  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    restart: unless-stopped
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      - MINIO_ROOT_USER=cloudforge
    env_file:
      - /opt/cloud-forge/compose.app.env

    volumes:
      - /opt/cloud-forge/data/minio:/data

    networks:
      - cloud-forge

networks:
  cloud-forge:
    name: cloud-forge
