services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.30.2
    restart: unless-stopped




    volumes:
      - /opt/cloud-forge/data/prowlarr:/config

    networks:
      - cloud-forge

networks:
  cloud-forge:
    name: cloud-forge
